//HintName: ReactiveInjection.GeneratorTests.ReactiveRoutingService.g.cs
// <auto-generated/>
// This file was automatically generated by the ReactiveInjection source generator.
// Do not edit this file manually since it will be automatically overwritten.
// ReSharper disable All
#nullable enable

using Microsoft.Extensions.Logging;

namespace ReactiveInjection.GeneratorTests
{
    [global::System.Diagnostics.DebuggerStepThroughAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ReactiveInjection.SourceGenerator", "1.0.0.0")]
    public class ReactiveRoutingService : global::ReactiveInjection.Routing.ReactiveRoutingServiceBase<ReactiveRoutingService>
    {
        private readonly global::Tree.Models.ViewModel3 _service0;
        private readonly global::System.IServiceProvider _service1;

        public ReactiveRoutingService(global::ReactiveInjection.Routing.IReactiveRouterHandler handler, global::Tree.Models.ViewModel3 service0, global::System.IServiceProvider service1)
            : base(handler, Loaders)
        {
            this._service0 = service0;
            this._service1 = service1;
        }

        private static readonly global::ReactiveInjection.Routing.ReactiveViewModelLoader<ReactiveRoutingService>[] Loaders = new global::ReactiveInjection.Routing.ReactiveViewModelLoader<ReactiveRoutingService>[]
        {
            new global::ReactiveInjection.Routing.ReactiveViewModelLoader<ReactiveRoutingService>(
                typeof(global::Tree.Models.ViewModel1),
                @"Load",
                @"VM1/{id}",
                r => r.Length == 2 && r[0].Equals(@"VM1", StringComparison.OrdinalIgnoreCase),
                async (s, r, ct) => (object)(await global::Tree.Models.ViewModel1.Load(r[1], s._service0, ct))),
            new global::ReactiveInjection.Routing.ReactiveViewModelLoader<ReactiveRoutingService>(
                typeof(global::Tree.Models.ViewModel2),
                @"Load",
                @"VM2",
                r => r.Length == 1 && r[0].Equals(@"VM2", StringComparison.OrdinalIgnoreCase),
                async (s, r, ct) => (object)(await global::Tree.Models.ViewModel2.Load(s._service0, ct))),
            new global::ReactiveInjection.Routing.ReactiveViewModelLoader<ReactiveRoutingService>(
                typeof(global::Tree.Models.ViewModel3),
                @"Load",
                @"VM3/{id:decimal}/{name}",
                r => r.Length == 3 && r[0].Equals(@"VM3", StringComparison.OrdinalIgnoreCase) && decimal.TryParse(r[1], out var _),
                async (s, r, ct) => (object)(await global::Tree.Models.ViewModel3.Load(decimal.Parse(r[1]), r[2], s._service1, ct))),
            new global::ReactiveInjection.Routing.ReactiveViewModelLoader<ReactiveRoutingService>(
                typeof(global::Tree.Models.ViewModel3),
                @"Load2",
                @"VM3/{b:bool}/{name}",
                r => r.Length == 3 && r[0].Equals(@"VM3", StringComparison.OrdinalIgnoreCase) && bool.TryParse(r[1], out var _),
                async (s, r, ct) => (object)(await global::Tree.Models.ViewModel3.Load2(bool.Parse(r[1]), s._service1, ct))),
            new global::ReactiveInjection.Routing.ReactiveViewModelLoader<ReactiveRoutingService>(
                typeof(global::Tree.Models.ViewModel4),
                @"Load",
                @"VM4/{id:int}/{name}",
                r => r.Length == 3 && r[0].Equals(@"VM4", StringComparison.OrdinalIgnoreCase) && int.TryParse(r[1], out var _),
                async (s, r, ct) => (object)(await global::Tree.Models.ViewModel4.Load(int.Parse(r[1])))),
            new global::ReactiveInjection.Routing.ReactiveViewModelLoader<ReactiveRoutingService>(
                typeof(global::Tree.Models.ViewModel5),
                @"Load",
                @"{Token}",
                r => r.Length == 1,
                async (s, r, ct) => (object)(await global::Tree.Models.ViewModel5.Load(r[0], s._service0, ct))),
        };
    }
}
