//HintName: Models.ModelItems.InjectedViewModel2.g.cs
// <auto-generated/>
// This file was automatically generated by the ReactiveInjection source generator.
// Do not edit this file manually since it will be automatically overwritten.
#nullable enable
namespace Models.ModelItems
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ReactiveInjection", "1.0.0.0")]
    partial class InjectedViewModel2
    {
        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.MethodImplOptions(System.Runtime.CompilerServices.MethodImplOptions.Synchronized)]
        protected void SetModel1(global::Models.ModelItems.Model1? value)
        {
            if (object.ReferenceEquals(this.Model1, value)) { return; }
            List<string> changed = new List<string>(capacity: 2)
            if (!global::System.Collections.Generic.EqualityComparer<int?>.Default.Equals(this.Model1?.Int, value.Int))
            {
                changed.Add("Int");
                this.RaisePropertyChanging("Int");
            }
            if (!global::System.Collections.Generic.EqualityComparer<bool?>.Default.Equals(this.Model1?.InitRequired, value.InitRequired))
            {
                changed.Add("InitRequired");
                this.RaisePropertyChanging("InitRequired");
            }
            this.RaisePropertyChanging("Model1");
            this.Model1 = value;
            this.RaisePropertyChanged("Model1");
            foreach (string prop in changed) { this.RaisePropertyChanged(prop); }
        }

        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Runtime.CompilerServices.MethodImplOptions(System.Runtime.CompilerServices.MethodImplOptions.Synchronized)]
        private void init_Model1()
        {
            if (this.Model1 != null!) { return; }
            this.Model1 = new global::Models.ModelItems.Model1(default(int)!)
            {
                InitRequired = default(bool)!,
            };
        }

        public int? Int
        {
            [global::System.Diagnostics.DebuggerStepThroughAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            get => this.Model1?.Int;
        }

        public bool? InitRequired
        {
            [global::System.Diagnostics.DebuggerStepThroughAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            get => this.Model1?.InitRequired;
        }


        ///<summary>
        ///    This is a comment
        ///    </summary>
        ///<remarks>These are remarks</remarks>
        public string? RequiredInit
        {
            [global::System.Diagnostics.DebuggerStepThroughAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            get => this.Model3?.RequiredInit;
        }

        public string GetOnly
        {
            [global::System.Diagnostics.DebuggerStepThroughAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            get => this.Model3?.GetOnly;
        }

        public double? Required
        {
            [global::System.Diagnostics.DebuggerStepThroughAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            get => this.Model3?.Required;
        }

        public global::Models.ModelItems.Model4 Class
        {
            [global::System.Diagnostics.DebuggerStepThroughAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            get => this.Model3?.Class;
        }

    }
}
