//HintName: ReactiveInjection.Tests.ModelInjection.InjectedViewModel2.InjectedViewModel3.g.cs
// <auto-generated/>
// This file was automatically generated by the ReactiveInjection source generator.
// Do not edit this file manually since it will be automatically overwritten.
// ReSharper disable All
#nullable enable
using ReactiveUI;
namespace ReactiveInjection.Tests.ModelInjection
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ReactiveInjection.SourceGenerator", "1.0.0.0")]
    partial class InjectedViewModel2
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ReactiveInjection.SourceGenerator", "1.0.0.0")]
        partial class InjectedViewModel3
        {

            ///<summary>
            ///    This is a comment
            ///    </summary>
            ///<remarks>These are remarks</remarks>
            [global::System.Diagnostics.DebuggerStepThroughAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
            public string? RequiredInit
            {
                [global::System.Diagnostics.DebuggerStepThroughAttribute()]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
                get => this.Model3?.RequiredInit;
            }

            [global::System.Diagnostics.DebuggerStepThroughAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
            public string? GetOnly
            {
                [global::System.Diagnostics.DebuggerStepThroughAttribute()]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
                get => this.Model3?.GetOnly;
            }

            [global::System.Diagnostics.DebuggerStepThroughAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
            public double? Required
            {
                [global::System.Diagnostics.DebuggerStepThroughAttribute()]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
                get => this.Model3?.Required;
            }

        }
    }
}
