//HintName: Tree.Models.ViewModelFactory.g.cs
// <auto-generated/>
// This file was automatically generated by the ReactiveInjection source generator.
// Do not edit this file manually since it will be automatically overwritten.
#nullable disable
namespace Tree.Models
{
    [global::System.ComponentModel.BrowsableAttribute(false)]
    [global::System.Diagnostics.DebuggerStepThroughAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ReactiveInjection", "1.0.0.0")]
    partial class ViewModelFactory
    {
        private readonly global::Tree.Models.Service _service0;
        private readonly global::System.Collections.Generic.List<int> _service1;
        private readonly global::System.Collections.Generic.List<int[]> _service2;
        private readonly global::System.IServiceProvider _service3;

        private readonly global::Tree.Models.SharedState _state0 = new global::Tree.Models.SharedState();
        private readonly global::System.Collections.ObjectModel.ObservableCollection<global::Tree.Models.SharedState> _state1 = new global::System.Collections.ObjectModel.ObservableCollection<global::Tree.Models.SharedState>();

        public ViewModelFactory(global::Tree.Models.Service service0, global::System.Collections.Generic.List<int> service1, global::System.Collections.Generic.List<int[]> service2, global::System.IServiceProvider service3)
        {
            this._service0 = service0;
            this._service1 = service1;
            this._service2 = service2;
            this._service3 = service3;
        }

        public global::Tree.Models.ViewModel1 ViewModel1(global::Tree.Models.Model model)
        {
            return new global::Tree.Models.ViewModel1(this._state0, model, this._service0, this._service1, this._service2);
        }

        public global::Tree.Models.ViewModel2 ViewModel2()
        {
            return new global::Tree.Models.ViewModel2(this._state0, this, this._service0, this._service3);
        }

        public global::Tree.Models.ViewModel3 ViewModel3(string str, string str2)
        {
            return new global::Tree.Models.ViewModel3(str, this._state1, str2);
        }

        public global::Tree.Models.ViewModel4 ViewModel4()
        {
            return new global::Tree.Models.ViewModel4(this._state0);
        }

        public global::Tree.Models.ViewModel5 ViewModel5(global::System.Collections.ObjectModel.ReadOnlyObservableCollection<global::Tree.Models.SharedState> parameter)
        {
            return new global::Tree.Models.ViewModel5(parameter);
        }

        public global::Tree.Models.ViewModel6 ViewModel6()
        {
            return new global::Tree.Models.ViewModel6();
        }
    }
}
