using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using ReactiveInjection.DependencyInjection;

namespace ReactiveInjection.Framework;

internal static class WriterHelpers
{
    public static void WriteFileHeader(this IndentedWriter writer, string nullable)
    {
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("// This file was automatically generated by the ReactiveInjection source generator.");
        writer.WriteLine("// Do not edit this file manually since it will be automatically overwritten.");
        writer.WriteLine("// ReSharper disable All");
        writer.WriteLine($"#nullable {nullable}");
    }
    
    public static void WriteClassAttributes(this IndentedWriter writer)
    {
        writer.WriteLine($"[global::{typeof(GeneratedCodeAttribute).FullName}(\"ReactiveInjection\", \"{Version}\")]");
    }

    public static void WriteDebuggerAttributes(this IndentedWriter writer)
    {
        writer.WriteLine($"[global::{typeof(DebuggerStepThroughAttribute).FullName}()]");
        writer.WriteLine($"[global::{typeof(DebuggerNonUserCodeAttribute).FullName}()]");
    }

    private static Version Version => typeof(WriterHelpers).Assembly.GetName().Version;
}